config/routes.rb
Rails.application.routes.draw do

  #get 'welcome/index'
  #get '/searches', to: 'searches#index', as: 'search'

  devise_for :users
  resources :users

  resources :users do
    resources :searches
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  # routes for user relationships
  resources :relationships, only: [:create, :destroy]

  root 'searches#index'
  get 'users/:id', to: 'searches#index'

  #get 'users', to:

  get '/users', to: 'users#index'

  get 'users/show'

  get 'welcome/index'

  get '/searches', to: 'searches#index', as: 'search'

  get '/users/:id/searches/new', to: 'searches#create'

  get '/searches/new', to: 'searches#new'

  post '/searches/new', to: 'searches#create'

  get '/searches/:id', to: 'searches#show'

	#resources :output
	#resources :main
	#root 'application#team'
end

app/models/user.rb
class User < ApplicationRecord
  after_save    :expire_user_all_cache
  after_destroy :expire_user_all_cache

  has_many :searches

  has_many :active_relationships,
  			class_name: "Relationship",
  			foreign_key: "follower_id",
  			dependent: :destroy
  has_many :passive_relationships,
  			class_name: "Relationship",
  			foreign_key: "followed_id",
  			dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  # Follows a user.
  def follow(other_user)
	following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
  	following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
  	following.include?(other_user)
  end

  # caching
  def self.all_cached
    Rails.cache.fetch('User.all') { all.to_a }
  end

  #user search history caching
  #def self.searches_cached
  #  Rails.cache.fetch('User.searches') { User.find(params[:id]).searches.to_a }
  #end

  # expire cache
  def expire_user_all_cache
    Rails.cache.delete('User.all')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  caches_action :show, :index

  def index
    @users = User.all_cached
    #@users = @users.paginate(page: params[:page], per_page: 7)
    #render 'index'
  end

  def show
  	# @user = current_user
    @user = User.find(params[:id])
    @searches = @user.searches
    #@searches = @user.searches_cached
  end

  def following
      @title = "Following"
      @user = User.find(params[:id])
      @users = @user.following.paginate(page: params[:page], per_page: 7)
      render 'show_follow'
  end

  def followers
      @title = "Followers"
      @user = User.find(params[:id])
      @users = @user.followers.paginate(page: params[:page], per_page: 7)
      render 'show_follow'
  end

  private
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        return user.id == current_user.id
    end

end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: {method: :delete}, remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/index.html.erb
<br>
<div id="rcorner">
  <table class="table table-hover table-bordered table-sm" style="width:600px;" align="center">
    <thead>
      <tr>
        <th style="text-align:center; width:100px; background-color:#EDE574; color:grey">Users</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <% cache user do %>
        <tr>
          <td style="padding: 10px; text-align:center; font-weight:bold;" class="align-middle">
            <%= link_to user.user_name, user_path(user.id), {:style => 'color:black'} %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="text-center">
   <button type="button" id="butt" >
     <%= link_to 'Back', search_path, {:style => 'color:#594F4F;'}%>
   </button>
</div>
<br>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<div class="d-md-flex h-md-100 align-items-center">

<!-- First Half -->
<div class="col-sm-4 p-0 bg-indigo h-md-100 user-info">
    <div class="text-white d-md-flex align-items-center h-100 p-5 text-center justify-content-center panel widget light-widget panel-bd-top">
        <div class="logoarea pt-5 pb-5">
            <div class="profile">
                <section id="profile_info">
                    <div class="profile-image">
                    	<% if @user.avatar.attached? %>
                    		<img src="<%=(url_for(@user.avatar))%>" class="rounded-circle" style="width:140px;height:140px">
                    	<% else %>
                    	   <%= image_tag("user-icon.jp2", size:"140x140", class: "rounded-circle") %>
                    	<% end %>
                    </div>
                    <!-- End of profile-image -->

                    <div class="profile-user-settings">
                    	<h1 class="profile-user-name"><%= @user.user_name %></h1>
                        <% if @user == current_user %>
                    	<button class="btn profile-edit-btn"><%= link_to "Edit Profile", edit_user_registration_path %></button>
                        <% end %>
                    </div>
                    <!-- End of profile-user-settings -->
                </section>
                <!-- End of profile_info section -->
                <section id="stats">
            	       <%= render 'users/shared/profile' %>
                </section>
                <!-- End of stats section -->
                <%= render 'users/shared/follow_form' if user_signed_in? %>
			</div>
        </div>
    </div>
</div>

<!-- Second Half -->

<div class="col-sm-8 p-0 h-md-100 searches">
    <div class="d-md-flex align-items-center h-md-100 p-5 justify-content-center">
    	<section class="c-posts">
	        <center><h1>Search History</h1></center>
            <ol style="font-size:17px">
            <% @searches.each do |search| %>
                <p><li><%= search.text %></li></p>
            <% end %>
            </ol>
            <% if @searches.size == 0 %>
                <% if @user == current_user %>
                <p>You haven't searched anything yet.</p>
                <% else %>
                <p><%= @user.user_name %> haven't searched anything yet.</p>
                <% end %>
            <% end %>
        </section>
    </div>
	<!-- .split(/\s+/, 11)[0...10].join(' ') -->
</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="d-md-flex h-md-100 align-items-center">

<!-- First Half -->
<div class="col-sm-4 p-0 bg-indigo h-md-100 user-info">
    <div class="text-white d-md-flex align-items-center h-100 p-5 text-center justify-content-center panel widget light-widget panel-bd-top">
        <div class="logoarea pt-5 pb-5">
            <div class="profile">
                <section id="profile_info">
                    <div class="profile-image">
                    	<% if @user.avatar.attached? %>
                    		<img src="<%=(url_for(@user.avatar))%>" class="rounded-circle" style="width:140px;height:140px">
                    	<% else %>
                    	   <%= image_tag("user-icon.jp2", size:"140x140", class: "rounded-circle") %>
                    	<% end %>
                    </div>
                    <!-- End of profile-image -->

                    <div class="profile-user-settings">
                    	<h1 class="profile-user-name"><%= @user.user_name %></h1>
                            <span><%= link_to "view my profile", @user %></span>
                    </div>
                    <!-- End of profile-user-settings -->
                </section>
                <!-- End of profile_info section -->
                <section id="stats">
            	       <%= render 'users/shared/profile' %>
                </section>
                <!-- End of stats section -->
			</div>
        </div>
    </div>
</div>

<!-- Second Half -->

<div class="col-sm-8 p-0 h-md-100">
    <div class="d-md-flex align-items-center h-md-100 p-5 justify-content-center">
        <section class="show-follow">
	        <center><h1><%= @title %></h1></center>
            <% if @users.any? %>
            <% @users.each do |user| %>
                <ul style="font-size:13px; list-style: none">
                    <li>
                        <% if user.avatar.attached? %>
                            <img src="<%=(url_for(user.avatar))%>" class="rounded-circle" style="width:50px;height:50px">
                        <% else %>
                            <%= image_tag("user-icon.jp2", size:"50x50", class: "rounded-circle") %>
                        <% end %>
                        <%= link_to user.user_name, user_path(user.id) %>
                    </li>
                </ul>
            <% end %>
            <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>
            <% end %>
        </section>

    </div>
</div>
</div>