config/routes.rb
Rails.application.routes.draw do

  #get 'welcome/index'
  #get '/searches', to: 'searches#index', as: 'search'

  devise_for :users
  resources :users

  resources :users do
    resources :searches
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  # routes for user relationships
  resources :relationships, only: [:create, :destroy]

  root 'searches#index'
  get 'users/:id', to: 'searches#index'

  #get 'users', to:

  get '/users', to: 'users#index'

  get 'users/show'

  get 'welcome/index'

  get '/searches', to: 'searches#index', as: 'search'

  get '/users/:id/searches/new', to: 'searches#create'

  get '/searches/new', to: 'searches#new'

  post '/searches/new', to: 'searches#create'

  get '/searches/:id', to: 'searches#show'

	#resources :output
	#resources :main
	#root 'application#team'
end

app/models/search.rb
class Search < ApplicationRecord
  after_save    :expire_search_all_cache
  after_destroy :expire_search_all_cache

  belongs_to :user, optional: true
  validates :text, presence: true
  validates :score, presence:true, numericality: { :less_than_or_equal_to => 100, :greater_than_or_equal_to => 0}


#for front page display
  def self.all_cached

    #only cache the top five searches
    Rails.cache.fetch('Search.all') { all.sort_by {|obj| -obj.score}[0..4].to_a }
    #Rails.cache.fetch('Search.all') { all.to_a }
  end

  def expire_search_all_cache
    Rails.cache.delete('Search.all')
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  caches_action :index, :show

  #these actions wont need login
  #skip_before_action :require_login, only: [:new, :create, :index]

  # GET /searches
  # GET /searches.json
  def index
    @user = current_user
    @searches = Search.all_cached
    #@searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    @user = current_user
    @search = Search.find(params[:id])
    # GET similar URLS FOR THIS SEARCH
    results = get_results(@search.text)
    @urls = results["urls"]

    @searche_ids = results["matching_ids"]

    #get scores first
    # To reduce load on db, I edited the search function
    # to return these scores at once, rather than doing
    # multiple calls
    @scores = results["matching_scores"]

=begin
    @searche_ids.each do |id|
       # results = get_results(Article.find(id).body)
       @scores << results["score"]
    end
=end

    #connect the urls with its corresponding score
    @similar_articles = {}
    @urls.each_with_index do | url, index|
      @similar_articles[url] = @scores[index]
    end

    #sort the urls based on their scores
    @similar_articles = @similar_articles.sort_by { |_key, value| -value }.to_h
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create

    #check if user signs in or not
    @search = nil
    @user = User.find(1) if User.count > 0
    if current_user.nil?
      @search = Search.create(search_params)
      #all the public search without signing in will be marked with user_id equals to 1
      if @user.nil?
        @user = User.new(user_name:"admin",email:"admin@newbie.com",encrypted_password:"012340", password:"012340")
        @user.id = 1
        @user.save!
      end
      @search = @user.searches.create(search_params)
      #@search.user_id = 0
    else
      @user = current_user
      @search = @user.searches.create(search_params)
      p @search
    end

    # GET SCORE FOR THIS SEARCH
    results = get_results(@search.text)
    @search.score = results["final_score"]
    @urls = results["urls"]
    # results["matching_ids"]

    #for testing, default score value 66
    #@search.score = 100 if @search.score.nil?

    respond_to do |format|
      if @search.save
        #format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.html { redirect_to "/searches/#{@search.id}", notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    expire_action :action => :index
    expire_action :action => :show
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    expire_action :action => :index
    expire_action :action => :show
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section."
        redirect_to new_login_url
      end
    end

    def get_results(search_text)
      DistributeReads.by_default = true
      results = {}
      matching_articles = Article.search(search_text).with_pg_search_rank
      total_score = 0

      counter = 0
      matching_ids = []
      matching_urls = []
      matching_scores = []
      for article in matching_articles do
        next if article.pg_search_rank < 0.4
        break if matching_urls.count > 25
        publication_score = get_publication_score(article.url)
        total_score += article.pg_search_rank * publication_score
        matching_scores.append(article.pg_search_rank * publication_score * 100)
        counter += 1
        matching_ids.append(article.id)
        matching_urls.append(article.url)
      end

      # COMPUTE FINAL SCORE
      # Start with picking the maximum score out of all matching scores.
      # For every subsequent score, divide it by 70 and add it to final_score.
      # Cap value of final_score to 99.
      saver = 0
      sorted_scores = matching_scores.sort.reverse
      for score in sorted_scores do
        if saver == 0 then
          saver = score
        else
          saver = saver + score / 70
        end
      end
      results["final_score"] = [saver, 99].min

      results["matching_ids"] = matching_ids
      results["urls"] = matching_urls
      results["matching_scores"] = matching_scores
      results
    end

    def get_publication_name(url)
      if url.nil?
        puts("URL NOT PARSABLE")
        return "unknown"
      end
      return 'usatoday' if url.include? 'usatoday'
      return 'washingtonpost' if url.include? 'washingtonpost'
      return 'wsj' if url.include? 'wsj'
      return 'nytimes' if url.include? 'nytimes'
      return 'aol' if url.include? 'aol'
      puts(url)
      if url.split('www.')[1].nil?
        x = url.split('.com')[0].split('.')[1]
        return x if not x.nil?
        url.split('.com')[0].split('http://')[1]
      else
        url.split('www.')[1].split('.')[0]
      end
    end

    def get_publication_score(url)
      publication_name = get_publication_name(url)
      publication_score_mapping = get_publication_score_mapping()
      return 0.5 if !publication_score_mapping.has_key?(publication_name.to_sym)
      return publication_score_mapping[publication_name.to_sym]
    end

    def get_publication_score_mapping()
      {
        "aol": 0.61,
        "wsj": 0.81,
        "nytimes": 0.78,
        "bloomberg": 0.8,
        "bbc": 0.9,
        "washingtonpost": 0.6,
        "usatoday": 0.2,
        "time": 0.7,
        "thesun": 0.1,
        "thepostgame": 0.13,
        "theguardian": 0.81,
        "telegraph": 0.68,
        "sfgate": 0.48,
        "reuters": 0.74,
        "people": 0.31,
        "nypost": 0.48,
        "nbc": 0.71,
        "nbcnews": 0.71,
        "msnbc": 0.71,
        "mashable": 0.1,
        "latimes": 0.69,
        "forbes": 0.83,
        "cnn": 0.68,
        "cnbc": 0.71,
        "buzzfeed": 0.11,
        "aljazeera": 0.75,
        "chicagotribune": 0.67,
      }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:text)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<div id="rcorner">
 <h2 style="text-align:center; color:white; font-family:Sans-serif;">Enter Text:</h2>
 <br>
 <%= form_with(model: search,url: searches_new_path,local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="center">
    <%= form.text_area :text, :cols => 40, :rows => 10 %>
  </div>
  <br>
  <div class="actions" style="text-align:center;">
    <%= form.submit 'Submit' %>
  </div>
 <% end %>
</div>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice" style="text-align:center;"><%= notice %></p>
<br>
<div id="rcorner">
  <h1 style="text-align:center">
    <span style="font-family:Gill Sans, Sans-serif; font-size:30px" class="text-white" data-toggle="tooltip" data-placement="right" title="Today it's a good day, eh?">
      News Feed Article
    </span>
  </h1>

  <table class="table table-hover table-bordered table-sm" style="width:600px;" align="center">
    <thead>
      <tr>
        <th style="text-align:center; width:100px; background-color:#EDE574; color:grey">Score</th>
        <th style="text-align:center; background-color:#F7DB4F; color:grey">Content</th>
        <th style="text-align:center; background-color:#E84A5F; color:white">Like</th>
      </tr>
    </thead>

    <tbody>
      <!-- sort the news feed articles based on their scores -->
      <% sorted_search = @searches.sort_by { |obj| -obj.score } %>
      <!-- only show the top five articles to the front page -->
      <% topfive = @searches.count < 5 ? @searches.count : 5 %>
      <!-- < % sorted_search.each do |search| %> -->
      <% topfive.times do |i| %>
        <% cache i do %>
        <tr>
          <td style="padding: 10px; text-align:center; font-weight:bold;" class="align-middle">
            <%= sorted_search[i].score %>
          </td>
          <td style="width: 100%; padding: 15px; text-align:center;" >
            <%= " \" #{sorted_search[i].text} \" " %>
          </td>
          <td style="padding: 15px; text-align:center;">
            <span onclick="myFunction(this)" class="heart"></span>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="text-center">
   <button type="button" id="butt" >
     <%= link_to 'Search', "/searches/new", {:style => 'color:#594F4F;'}%>
   </button>
</div>
<br>

app/views/searches/new.html.erb
<br>
<%= render 'form', search: @search %>

<br>

<div class="text-center">
   <button type="button" id="butt" >
     <%= link_to 'Back', search_path, {:style => 'color:#594F4F;'}%>
   </button>
</div>

<!-- searches_path -->

app/views/searches/show.html.erb
<p id="notice" style="text-align:center;"><%= notice %></p>

<br>

<div class="card kard" style="width: 18rem;">
  <div class="card-img-top Box" style="text-align:center; font-size:60px; background-color:#F9CDAD;">
    <%= @search.score %>
  </div>
  <br>
  <div class="card-body kard-body">
    <p class="card-text"><%= "\" #{@search.text} \"" %></p>
  </div>
</div>

<div onclick="myFunction(this)" class="heart"></div>
<br>


<% if !@similar_articles.nil? %>
  <span>
    <p style="text-align:center; font-weight:bold;">Similar Articles:</p>
  </span>
<% end %>

<div class="card kard" style="width: 20rem; text-align:center;">
  <% if @similar_articles.nil? %>
    <%= "No Similar Urls found." %>
  <% else %>
    <%  @similar_articles.each do |url, score|  %>
      <div style="text-align:left; font-weight:bold;">
        <%= score.round %>
        <span class="divider"></span>
        <%= link_to url[0..28], url, title: url  %>
      </div>
    <% end %>
  <% end %>
</div>

<!-- < %= link_to 'Edit', edit_search_path(@search) %> -->
<br>
<br>

<div class="text-center">
   <button type="button" id="butt" style="padding:15px 23px;">
     <% if !@user.nil? %>
      <%= link_to 'Continue', "/users/#{@user.id}/searches/new", {:style => 'color:#594F4F;'}%>
    <% else %>
      <%=  link_to 'Continue', "/searches/new", {:style => 'color:#594F4F;'} %>
    <% end %>
   </button>
   <div class="divider"></div>
   <button type="button" id="butt">
     <%= link_to 'Home', "/searches", {:style => 'color:#594F4F;'}%>
     <!-- searches_path -->
   </button>
</div>